from tkinter import *
#from test import *
class Interface:
    def __init__(self):
        #-------GUI-------------------------#
        self.root = Tk()
        self.root.title(f'<< O PRISIONEIRO >>')
        self.root['bg'] = 'black'
#------------------------------------#
        #frame_historia = Frame(root)
        #frame_escolha = Frame(root)
        self.img = PhotoImage(file='imagens/prisioneiros.png')
        #----------------------------------------#
        self.titulo = Label(self.root,
                    text='<< O PRISIONEIRO >>',
                    fg='white',
                    font='arial',
                    justify='center',
                    bg='black',
                    width=20).pack()
        self.label_img = Label(self.root, image=self.img,
                        relief='flat',
                        width=400,
                        bg='black').pack()
        self.bt_iniciar = Button(self.root,
                            text='INICIAR HISTÓRIA...',
                            justify='right',
                            border=4,
                            relief="groove",
                            width=20,
                            height=2,
                            fg='black',
                            font='arial 12 bold',
                            bg='white',
                            command= self.abrir_novo).pack(side=BOTTOM)
        self.frase = Label(self.root,
                    text='''ESSA É UMA HISTÓRIA INTERATIVA
        E TEM VÁRIOS FINAIS''',
                        fg='red',
                        font='arial',
                        bg='black').pack(side=BOTTOM)
        self.root.geometry('500x400+400+100')
        self.root.resizable(0,0)
        self.root.mainloop()
        
        self.frases = [
#0
'''Você agora consegue enxergar melhor o que está a sua frente...
parece uma prisão em um tipo de caverna...assustado...
vê seu melhor amigo está acorrentado pelos pés a um tipo de cano...
e você também...O que você faz?''',
#1
'''Ele diz que não se lembra de como chegou ali, só que estava bebendo em um bar e depois apagou,
quando viu estava aqui, faz mais de uma semana e ninguém aparece...estou faminto e não sei se vou aguentar mais um dia...disse ele...
O que você diz a ele?''',
#2
'''Seu amigo então se acalma e vocês procuram pelo chão algo que possa ajudar vocês..
então você encontra uns pequenos pedaços de metais que podem usar como lockpick, tecnicas aprendidas na época dos escoteiros...
depois de um bom tempo, vocês estão libértos das correntes, e decidem revirar o local...
nas paredes...olhando mais de perto vocês encontram uma espécie de enigma que diziam que se resolvessem seriam soltos...''',
 #3 FIM 1
'''Após descobrirem a charada, do nada uma certa parte da parede fica mole e eles então começam a bater nela...
fazendo um buraco e mostrando um tunel para fora da prisão...
eles com muita exaustão...atravessam o tunel e descobrem estar em uma ilha, onde tem um barco os esperando e uma carta...
que dizia:... Vocês foram meus escolhidos para meus teste... obrigado por participarem...e não morreram hahaha...
então vocês vão embora e procuram a polícia...contando tudo, quando voltam a ilha, não tinha nada...
se passaram por loucos... então...decidem procurar os dois por si só até encontrarem o responsável...e esse é o FIM!''',
#4
'''Você fica esperto com seu amigo, ele começa agir estranho...do nada ele começa amorder sua perna, e te atacar...
vocês lutam e sem pensar...acidentalmente você usa a faca nele, e consequêntemente ele acaba morrendo...
depois de ver o corpo dele cheio de sangue por horas, aparece alguns homens com jalécos brancos e te soltam...
dizendo que issp era um experimento para testar o quanto uma pessoa pode aguentar até chegar ao canibalismo...
você foi só um rato de laboratório...disse eles... então você?''',
#5 FIM 2
'''Ao entrar na sala de execução você ouve um tiroteio...muitos sons de tiros, então pronto para morrer...
chega um esquadrão da swat para te salvar e os outros iguais a você...
essa operação ocorria a anos mas somente agora encontramos eles...
disse o capitão da operação...e então você volta para casa, e diariamente vai a psicóloga para apagar tudo aquilo da memória...FIM!''',
#6 FIM 3
'''Levado por dois guardas, você acerta um na garganta com a faca e rouba sua arma e atira no outro antes que ele reaja...
então você vai atrás de todos os cientistas que te prenderam e os fazem pagar...
tendo sua vingança completa, você acaba descobrindo que na verdade eles estavam tentando descobrir uma cura para um vírus onde transforma as pessoas em canibais...
e esse vírus afetou o mundo todo...restando poucos sobreviventes...
após tudo isso você se pergunta...Sou um herói ou vilão?...FIM!''',
#7
'''Seu amigo vê você com a faca e diz para tomar cuidado, como previsto... as correntes não se partiram...
então você com raiva grita por socorro!... mas ninguem responde... porém alguém joga uma carta pela fechadura da porta da prisão...
o que você faz?''',
#8
'''Na carta dizia o seguinte:...A sua única chance de escapar esta dentro do seu amigo...
para te ajudar deixei uma faca ai...que os jogos começem hahaha!... sem saber o que fazer você fica com medo de mostrar a carta para seu amigo que estava perguntando o que ela dizia...
entâo, o que você faz?''',
#9 FIM 4
'''Você então esfaqueia seu amigo e faz brutalidades... até encotrar duas chaves...
uma para seu cadeado que prendia seu pé... outra devia ser para a porta... porém a chave não funcionava... ou seja...
você foi enganado!...então agora você ficará preso e ficará com o que fez na consiência...FIM!''',
#10 FIM 5
'''Quando você mostrou...seu amigo ficou assustado...porém confiou em você por ter mostrado...
tentando de várias formas de fugir...se passaram horas...então aparece 2 homens mascárados, falando que um de nos poderá ir e o outro terá de ficar...
como você foi leal a seu amigo, ele me forçou a ir...então com agressividade os mascárados te doparam e você acordou em sua casa...
pensando se aquilo foi um sonho ou era real...FIM!''',
#11 FIM 6
'''Você diz que a carta dizia apenas que não tinha saída, então seu amigo entristecido...
diz... que pena... você era um dos melhores...ele tira uma chave do bolso e se liberta...abre o portão...
e antes de ir embora e te deixar preso ele fala:...eu planejei isso para testar as pessoas... sua lealdade foi testada e você não passou...
Sinto muito...então o que restou a você foi ficar preso ou acabar com isso logo com a faca que tinha...FIM!''',
#12
'''Com a visão mais clara da cela, você enxerga um barril encostado na parede... com passar do tempo...
quase acabando o dia, você decide revirar os bolsos, e encontra uma chave estranha...nunca vista antes...
aparentemente ela abre apenas um dos cadeados que prendem você e seu amigo... o que você faz?''',
#13 FIM 7
'''Seu amigo agora esta liberto, e então ele do nada grita: COOOORRTA!, e então aparece vários caras engravatados e com armas na cintura...
seu amigo diz que é da CIA e isso era um teste de lealdade, onde você passou com exito, e agora tambem é um agente...
então vocês voltam para casa e se preparam para sua primeira missão...PARABÉNS agente!...FIM''',
#14
'''Agora que você esta livre, você anda até o barril, e tem a idéia de empurra-lo, e vê um tunel escuro e tenebroso...
você cogita ir, todo animado você grita que achou uma saída e olha para seu amigo, mas ele acaba de falecer...
e com ele entre seus braços está uma carta... mas esta muito escuro para ler a carta ou para ver aonde o tunel da...
o que você faz?''',
#15 FIM 8
'''A carta dizia o seguinte:...Caro amigo, você foi meu único amigo esse tempo todo por mais que a situação esteja díficil aqui...
sei que iremos achar uma saída juntos, eu não te abandono e nem você a mim... 
assinado: seu melhor amigo e irmão... (SIM...ele era seu irmão).. com sentimento abalado...
você desiste de encontrar uma saída e decide ficar ao lado de seu irmão...
pois ele era a única familia que tinha... não se sabe quanto tempo passou mas nínguem nunca mais soube de você...FIM!''',
#16 FIM 9
'''Você se rasteja pelo tunel, o caminho é longo, se pergunta quem fez ele... com o fósforo quase apagando...
você vê uma luz...chegando mais perto... você se depara com alienigenas andando pelas ruas...
aparentemente vocês são prisioneiros deles...
com cautéla...você acerta um que estava distraido e rouba uma chave igual a que estava no seu bolso...
então você volta para libertar seu amigo... porém bem na hora eles abrem a cela e começam a disparar...
acabando com você e seu amigo...com um fechamento triste...aparentemente esse foi seu... FIM!''',
#17 FIM 10
'''Você entra em um sono profundo e acorda em sua cama...
lembra que bebeu um pouco a mais na noite passada com seu melhor amigo...
Tudo era apenas um sonho!... e você então volta à sua vida normal... FIM!''',
#18
'''Como fazia dias que seu amigo não se alimentava... ele acaba falecendo...
Você surtado começa Andar pelo lugar...
você encontra um tipo de siringa, ela está um pouco cheio mas não da importância...
você continua andando para ver uma saída e vê a porta da cela...tenta enxergar, porém não vê ninguem...
entediado... você começa a esfregar a faca na parede...logo após isso você ouve alguém gritando do outro lado...
então você:''',
#19
'''Ela diz que é uma mulher e acordou numa cela escura e gelada...você diz o mesmo, então vocês começam a conversar e trocar informações pessoais...
onde logo após isso, ela mostra fazer parte disso...que estava apenas te enganando para saber mais sobre você e sua familia...
sem saber o que fazer...
você fica remoendo isso na cabeça, que foi enganado e agora sua família corre perigo...então, acidentalmente...
você derruba a seringa, que nela tinha uma mensagem escondida... dizendo... USA-ME...então você:''',
#20 FIM 11
'''Ao usar a seringa você se sente meio estranho, então vai se apoiar na parede e com o mínimo de esforço a quebra...
você aparentemente ganhou poderes, e vai atrás da mulher que te enganou...
ao encontra-la... você a reconhece pela voz, e ela esta vestida com um jaléco, num laboratório...cheio de cientistas...
ela explica que aquilo era necessário para que você usa-se a seringa... este é um experimento da área cinquenta e um...
onde você concordou em apagarmos sua memória recente e testarmos a nossa nova fórmula do super-soldado...
depois da explicação você foi designado para uma missão ultra-secreta...e você acabou se tornando uma lenda para todo o exército...FIM!''',
#21
'''Não, eu que pergunto... disse ela, vocês conversam para passar o tempo, até que acham uma fresta entre sua cela e a dela...
pequena mas pode ver um ao outro... vocês continuam conversando por ali até chegar uma carta na cela de cada um...
você vai e lê a carta: que diz... Sua liberdade custa uma vida...
se tirar a vida dela, você estará livre... perto de você tem uma seringa... faça-a tomar, ela não é quem diz ser...
ela é uma assassina e merece morrer pelo que fez...se não fizer...irei atrás do seus parentes...então você:''',
#22 FIM 12
'''Ela aceita tomar a seringa, desde que prometa que quando sair, irá cuidar da sua filha que não tem mais ninguém além dela...
você então promete e da a seringa atravéz da fresta... e assim foi feito... como prometido você foi solto e foi atrás da filha da mulher...
e foi a melhor coisa que aconteceu para você, você e a criança criaram uma conexão muito grande que fez esquecer tudo aquilo...
e acabou com a solidão que você tinha antes de tudo aquilo...FIM!''',
#23
'''Ela confessa, mas explica que tudo que fez foi por sua filha... quem nos prendeu aqui é um velho inimigo meu... 
mas eu tenho um geito de escapar...disse ela...("você então ouve um barulho de luta na cela da mulher),..
assustado... você pergunta o que ouve... então do nada ela abre a sua porta e te tira de lá...
então você diz para escapar...porém ela pede sua ajuda para acabar com quem os prendeu aqui... então você:''',
#24 FIM 13
'''Vocês vão com tudo pra cima do cara, você descobre que ele é um serial killer famoso procurado por toda FBI e antes dela matar ele...
ele diz:... finalmente acabou comigo parceira...
você então começa a surtar e sem pensar duas vezes pega uma arma e atira nela... mas como ela tem mais prática...
ela o acerta primeiro e o deixa morrer ali...dizendo... não era pra ser assim, sinto muito...FIM!''',
#25 FIM 14
'''Voce decide fugir... e então...anos depois... você reencontra a mulher e sua filha... 
e vocês começam a conversar e criam uma relação muito boa, ela diz que o procurou por que foi a única pessoa que foi sinceira com ela mesmo numa prisão...
a questionando ao invés de força-la a morrer...
e isso valia muito pra ela...então vocês se conhecem melhor e assim termina a história...FIM!''']
        
        self.escolha = [
#0 
'''1 - PERGUNTAR A SEU AMIGO O QUE ACONTECEU.
2 - TENTAR CORTAR AS CORRENTES COM A FACA
3 - ACENDER OUTRO FOSFORO PARA VER SE O QUE TEM NO RESTO DA CELA.

escolha: ''',
#1
'''1 - CALMA, VAMOS ACHAR UMA SAÍDA.
2 - ESSA HISTÓRIA NÃO FAZ SENTIDO, VOCE ESTA MENTINDO PARA MIM.

escolha: ''',
#2
'O que é, o que é? Quanto mais se tira mais se aumenta.  DICA: "B_____"',
#3
'''1 - ACEITA O FATO DE TER MATADO SEU AMIGO E SER EXECUTADO POR ELES.
2 - USA SUA FACA E TODAS HABILIDADES QUE GANHOU NO EXERCITO PARA MASSACRAR TODOS DAQUELE LUGAR.

escolha: ''',
#4
'''1 - ACENDE SEU ULTIMO FOSFORO E LÊ A CARTA.
2 - DEIXA SEU AMIGO LER A CARTA POIS VOCÊ ESTA UM POUCO SONOLENTO AINDA.
3 - VOCÊS DOIS LEEM A CARTA JUNTOS.

escolha: ''',
#5
'''1 - PRA ESCAPAR VALE TUDO!!!.
2 - MOSTRAR A CARTA PARA SEU AMIGO.
3 - MENTIR PARA SEU AMIGO.

escolha: ''',
#6
'''1 - LIBERTA SEU AMIGO, POIS ELE ESTA MAIS FRACO.
2 - SE LIBERTA PARA TENTAR ACHAR UMA SAÍDA.

escolha: ''',
#7
'''1 - USA O ÚLTIMO FÓSFORO PARA LER A CARTA.
2 - USA O ÚLTIMO FÓSFORO PARA VER AONDE ESSE TUNEL IRÁ DAR.

escolha: ''',
#8
'''1 - PERGUNTA QUEM ELA É
2 - PERGUNTA SE ELA ESTA FAZENDO ISSO COM VOCÊ

escolha: ''',
#9
'''1 - << USA A SERINGA! USA SERINGA!! USA SERINGA!!! >>

escolha: ''',
#10
'''1 - A CONVENCE A TOMAR A SERINGA
2 - PERGUNTA SE É VERDADE O QUE A CARTA DIZIA

escolha: ''',
#11
'''1 - AJUDAR A MULHER
2 - FUGIR

escolha: ''']
    
    def abrir_novo(self):
        #como se fosse criar uma interface normal, porem utilizando a funçao TopLevel()
        #pode criar qualquer widget normalmente
        self.root.destroy()
        self.top = Tk()
        self.top['bg'] = 'black'
        self.top.title('O PRISIONEIRO')
        self.top.geometry('500x400+400+100')
        self.top.resizable(0,0)
        lb = Label(self.top, text='Nome:', fg='white').grid(row=0, column=0)
        self.nome = Entry(self.top,textvariable="",justify='center').grid(row=0, column=1)
        
        
        
        
        

prisioneiro = Interface()
